[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_solana = "BTc32GfyocV5yZvSqvLvyefkLftyHfG92Sxao2KaLqiD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/abhi3700/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
